AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaClustalRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  clustal:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: exports.exchangetoken = function(event, context) {  context.succeed('OK');};
      Description: clustal
      Handler: index.clustal
      Role: !GetAtt 'LambdaClustalRole.Arn'
      Runtime: nodejs8.10
      MemorySize: 512
      Timeout: 20
    DependsOn: LambdaClustalRole
Outputs: {}
